import Hero from "@/components/pages/home/Hero";
import SignInSection from "@/components/pages/home/SignIn";

export const metadata = {
  title: "Beranda",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <Hero/>
      <SignInSection />
    </>
  );
}
